#Sonar organization (required)
sonar.organization=prueba32
#sonar project Key (required)
sonar.projectKey=prueba32_prueba
sonar.token=c37a44c59fc1ff545bd25f6cef3339a580be99bd
#Sonar projectName. The name that appears on a Sonar
dashboard (required)
sonar.projectName=praktika
#Maven version. (required)
sonar.projectVersion=0.0.1
#Path with java code (required)
#Helbide erlatiboa
sonar.sources=src
sonar.test=src/test/java
#All paths that contain test (optional)
tests=src
#Paths where the binaries of the project are located
(required)
binaries=bin
sonar.java.binaries=bin
# The project languaje (java for defect)
sonar.language=java
sonar.host.url=https://sonarcloud.io
sonar.dynamicAnalysis=reuseReports
sonar.exclusions=src/test/**,**/AñadirSaldo.java